### ISSUE TITLE
Feature requests / Improvements - Overview

### ISSUE THREAD

**Issue by Starlight220** [cwarwicker/discord-Writer-Bot#79]
Due to the many feature requests in the `#questions` and `#suggestions` in the support Discord, I'm opening this issue to track them so they don't get lost. I'll update this post.

### Fixes/Improvements
- [ ] Make bot threadsafe/atomic to solve problems such as the double-reporting issue.
- [ ] Word count submission phase should be considered as an active sprint.
- [ ] End count submission phase immediately if there are no sprinters with word counts (#75).
- [ ] Correctly handle `!sprint status` in word count submission phase (#75).
- [ ] Give the same XP for tied sprinters (#47).
- [ ] Fix remind command (#74, #69)

### New features
- [ ] Add `default_sprint_length` setting (used by `!sprint start`)
- [ ] Update bot for Discord Threads (I'm not sure that the discord library used in the bot supports them)
- [ ] Add `!project list by [status]`
- [ ] Deprecate (?) `edit` flag for sprints and replace it with `no-word-count` or similar.
- [ ] Add "sprint starting" warning and default warn time setting (#59).
- [ ] Option to disable commands (#30)
- [ ] Track (daily) goal completion streaks

@cwarwicker any thoughts?

**Comment by cwarwicker** [comment]
- [ ] Ability to have multiple genres for a project.
